it didnt like the quote in the cypress attribute [PT #184501425]
caused:
Can't run because no spec files were found.
We searched for specs matching this glob pattern:
  > /codebuild/output/src201357736/src/"cypress/e2e/homepage/*,cypress/integration/otherpages/*"
Error: Command failed with exit code 1: cypress run --record false --spec=\"cypress/e2e/homepage/*,cypress/integration/otherpages/*\"